// <auto-generated />
using System;
using LearningManagement.Occupation.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningManagement.Occupation.Infrastructure.Shared.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201123035_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Abilities.Ability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AbilityTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityTypeId");

                    b.ToTable("Abilities", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.AbilityTypes.AbilityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AbilityTypes", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationDegrees.EducationDegree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EducationDegrees", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationFieldSpecializations.EducationFieldSpecialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("EducationFieldId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EducationFieldId");

                    b.ToTable("EducationFieldSpecializations", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationFields.EducationField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EducationFields", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Industries.Industry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Industries", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.InterestTypes.InterestType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterestTypes", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Interests.Interest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InterestTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestTypeId");

                    b.ToTable("Interests", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.JobActivities.JobActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JobActivities", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationTypes", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("AcceptedDate")
                        .HasColumnType("date");

                    b.Property<int?>("AcceptedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LogoImg")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OrganizationTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Personalities.Personality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Personalities", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.SkillTypes.SkillType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillTypes", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Skills.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("SkillTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Abilities.Ability", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.AbilityTypes.AbilityType", "AbilityType")
                        .WithMany("Abilities")
                        .HasForeignKey("AbilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("AbilityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.WithOwner()
                                .HasForeignKey("AbilityId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("AbilityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.WithOwner()
                                .HasForeignKey("AbilityId");
                        });

                    b.Navigation("AbilityType");

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.AbilityTypes.AbilityType", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("AbilityTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("AbilityTypeId");

                            b1.ToTable("AbilityTypes");

                            b1.WithOwner()
                                .HasForeignKey("AbilityTypeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("AbilityTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("AbilityTypeId");

                            b1.ToTable("AbilityTypes");

                            b1.WithOwner()
                                .HasForeignKey("AbilityTypeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Department", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.Organizations.Models.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationDegrees.EducationDegree", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("EducationDegreeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("EducationDegreeId");

                            b1.ToTable("EducationDegrees");

                            b1.WithOwner()
                                .HasForeignKey("EducationDegreeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("EducationDegreeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("EducationDegreeId");

                            b1.ToTable("EducationDegrees");

                            b1.WithOwner()
                                .HasForeignKey("EducationDegreeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationFieldSpecializations.EducationFieldSpecialization", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.EducationFields.EducationField", "EducationField")
                        .WithMany("EducationFieldSpecializations")
                        .HasForeignKey("EducationFieldId")
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("EducationFieldSpecializationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("EducationFieldSpecializationId");

                            b1.ToTable("EducationFieldSpecializations");

                            b1.WithOwner()
                                .HasForeignKey("EducationFieldSpecializationId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("EducationFieldSpecializationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("EducationFieldSpecializationId");

                            b1.ToTable("EducationFieldSpecializations");

                            b1.WithOwner()
                                .HasForeignKey("EducationFieldSpecializationId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("EducationField");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationFields.EducationField", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("EducationFieldId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("EducationFieldId");

                            b1.ToTable("EducationFields");

                            b1.WithOwner()
                                .HasForeignKey("EducationFieldId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("EducationFieldId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("EducationFieldId");

                            b1.ToTable("EducationFields");

                            b1.WithOwner()
                                .HasForeignKey("EducationFieldId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Industries.Industry", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("IndustryId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("IndustryId");

                            b1.ToTable("Industries");

                            b1.WithOwner()
                                .HasForeignKey("IndustryId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("IndustryId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("IndustryId");

                            b1.ToTable("Industries");

                            b1.WithOwner()
                                .HasForeignKey("IndustryId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.InterestTypes.InterestType", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("InterestTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("InterestTypeId");

                            b1.ToTable("InterestTypes");

                            b1.WithOwner()
                                .HasForeignKey("InterestTypeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("InterestTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("InterestTypeId");

                            b1.ToTable("InterestTypes");

                            b1.WithOwner()
                                .HasForeignKey("InterestTypeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Interests.Interest", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.InterestTypes.InterestType", "InterestType")
                        .WithMany("Interests")
                        .HasForeignKey("InterestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("InterestId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("InterestId");

                            b1.ToTable("Interests");

                            b1.WithOwner()
                                .HasForeignKey("InterestId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("InterestId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("InterestId");

                            b1.ToTable("Interests");

                            b1.WithOwner()
                                .HasForeignKey("InterestId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("InterestType");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.JobActivities.JobActivity", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("JobActivityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("JobActivityId");

                            b1.ToTable("JobActivities");

                            b1.WithOwner()
                                .HasForeignKey("JobActivityId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("JobActivityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("JobActivityId");

                            b1.ToTable("JobActivities");

                            b1.WithOwner()
                                .HasForeignKey("JobActivityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("OrganizationTypeId");

                            b1.ToTable("OrganizationTypes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationTypeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("OrganizationTypeId");

                            b1.ToTable("OrganizationTypes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationTypeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", "OrganizationType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrganizationTypeId")
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("OrganizationType");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Personalities.Personality", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("PersonalityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("PersonalityId");

                            b1.ToTable("Personalities");

                            b1.WithOwner()
                                .HasForeignKey("PersonalityId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("PersonalityId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("PersonalityId");

                            b1.ToTable("Personalities");

                            b1.WithOwner()
                                .HasForeignKey("PersonalityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.SkillTypes.SkillType", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("SkillTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("SkillTypeId");

                            b1.ToTable("SkillTypes");

                            b1.WithOwner()
                                .HasForeignKey("SkillTypeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("SkillTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("SkillTypeId");

                            b1.ToTable("SkillTypes");

                            b1.WithOwner()
                                .HasForeignKey("SkillTypeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Skills.Skill", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.SkillTypes.SkillType", "SkillType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("SkillId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("SkillId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SkillType");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.AbilityTypes.AbilityType", b =>
                {
                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.EducationFields.EducationField", b =>
                {
                    b.Navigation("EducationFieldSpecializations");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.InterestTypes.InterestType", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.SkillTypes.SkillType", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
