// <auto-generated />
using System;
using LearningManagement.Occupation.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningManagement.Occupation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250125081908_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationTypes", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("AcceptedDate")
                        .HasColumnType("date");

                    b.Property<int?>("AcceptedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Code")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LogoImg")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OrganizationTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Models.Department", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.Organizations.Models.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("OrganizationTypeId");

                            b1.ToTable("OrganizationTypes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationTypeId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationTypeId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("OrganizationTypeId");

                            b1.ToTable("OrganizationTypes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationTypeId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", "OrganizationType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrganizationTypeId")
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("OrganizationId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("OrganizationType");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.OrganizationTypes.OrganizationType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Organizations.Models.Organization", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
