// <auto-generated />
using System;
using LearningManagement.Occupation.Infrastructure.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningManagement.Occupation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120101229_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Companies.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprovedAtUtcDateTime")
                        .HasColumnType("bigint");

                    b.Property<long>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CertificateCode")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsViewable")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Companies.Models.Company", b =>
                {
                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("CompanyId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("CompanyId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Departments.Models.Department", b =>
                {
                    b.HasOne("LearningManagement.Occupation.Domain.Companies.Models.Company", "Company")
                        .WithMany("Department")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Framework.Data.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("CreatedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAtUtcDateTime");

                            b1.Property<long?>("CreatedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("CreatedByUserId");

                            b1.Property<DateTime?>("ModifiedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedAtUtcDateTime");

                            b1.Property<long?>("ModifiedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("ModifiedByUserId");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.OwnsOne("Framework.Data.SoftDelete.SoftDeleteInfo", "SoftDeleteInfo", b1 =>
                        {
                            b1.Property<long>("DepartmentId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("DeletedAtUtcDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAtUtcDateTime");

                            b1.Property<long?>("DeletedByUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("DeletedByUserId");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("DepartmentId");

                            b1.ToTable("Departments");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SoftDeleteInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagement.Occupation.Domain.Companies.Models.Company", b =>
                {
                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
